version: "3"

services:
  mongo:
    image: mongo:latest
    command: mongod --port 2717
    networks:
      static-network:
        ipv4_address: 172.18.0.2
    ports:
        - 2717:27017
    volumes:
#    - ~/Docker_images/mongoDB_image:/data/db
    - mongo_data:/data/KitchenRecipesApp_data


networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet : 172.18.0.0/16

volumes:
  mongo_data:
    driver: local