version: "3"

services:
  postgres:
    image: postgres:latest
    networks:
      static-network:
        ipv4_address: 172.18.0.2
    ports:
      - 5432:5432
    volumes:
    - /data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet : 172.18.0.0/16

#volumes:
#  postgres_data:
#    driver: local
##    /data/postgres
