# Generated by Django 3.1.1 on 2020-09-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_squashed_0005_auto_20200921_0032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comments',
        ),
    ]
