# Generated by Django 3.1.1 on 2020-09-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_auto_20200921_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
