# Generated by Django 3.1.1 on 2020-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_delete_comment_squashed_0006_auto_20201003_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_from',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
