# Generated by Django 3.1.1 on 2020-10-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_recipe_recipe_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='times_visited',
            field=models.IntegerField(blank=0, default=0),
        ),
    ]
