# Generated by Django 3.1.1 on 2020-09-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_auto_20200921_0030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
