# Generated by Django 3.1.1 on 2020-10-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0005_auto_20201003_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prepare_dish_recipe',
            field=models.TextField(max_length=2000),
        ),
    ]
