# Generated by Django 3.1.1 on 2020-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0006_auto_20201003_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prepare_dish_recipe',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_from',
            field=models.URLField(blank=True),
        ),
    ]
